services:
  - type: web
    name: gradebook-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gradebook-database
          property: connectionString

databases:
  - name: gradebook-database
    databaseName: gradebook
    plan: free
